Part 1
Daniela0531/Android-Mipt-Project-2024-Zavidonova pull request #1
Opened 2024-04-06 15:14 UTC by Daniela0531

2024-04-13 12:41 UTC, Ksalim01 commented
В приложении нет почти ничего. Навигация на базе нескольких активити насколько я вижу. В целом хочется понять смысл приложения, т.к. запуская его, я кроме двух кнопок снизу, ничего не вижу. Приложение крешится на старте, если в системе темная тема. В общем трудно поставить что-то больше 0 баллов, поэтому жду исправлений. Следуйте требованиям https://docs.google.com/document/d/14dGZQKMcc6ofHFYMppv8MXFoE3IXsDvw9czFcwDw_kg/edit

2024-04-13 12:41 UTC, Ksalim01 requested changes
См комментарий выше

2024-04-15 20:29 UTC, DzhangirliEmil commented
Распишу подробно по пунктам и напишу, какие есть дальнейшие опции:

Текущее количество баллов - 1
1. было требование использовать NavigationManager, а так же только одно activity. Здесь же этого нету, так что **0 баллов**
2. Не вижу такого в коде - **0 баллов**
3. Креш при переключении темы, ибо не задан ресурс - **0 баллов**
4. не адаптирован - **0 баллов**
5. UI очень скудный, но можно оценить в **1 балла** 
6. Сохранения состояния в bundle нету - **0 баллов**
7. Не реализовано - **0 баллов**
8. Не реализовано - **0 баллов**

Если до 21 апреля реализуешь пункты 1, 3, 4, 5 и 8, то можно будет получить за них полный балл. 
Если реализуешь - призывай салима, он проверит и баллы выставит. На данный момент балл - 1

2024-04-15 20:30 UTC, DzhangirliEmil commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +    lateinit var register: Button
свойства приватные должны быть

2024-04-15 20:30 UTC, DzhangirliEmil commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +    }
зачем ето тут

2024-04-15 20:31 UTC, DzhangirliEmil commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +    }
эти строчки писать не обязательно)

2024-04-15 20:32 UTC, DzhangirliEmil commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +    }
Нигде не используются? Зачем они?

2024-04-15 20:33 UTC, DzhangirliEmil commented
В общем по коду очень много вопросов. Будешь готова исправить в дедлайн - призывай, Салим пройдется по всему коду. На всякий случай - есть минимальные требования к проекту https://docs.google.com/document/d/1G03zAA_2NNgPZoi9VdLLTLw10PHhu_DVS-ku7zacIRM/edit#heading=h.zd4xtzhqtde7

2024-04-19 11:24 UTC, Daniela0531 commented
добавила ночную тему и адаптацию под русский язык

2024-04-21 18:41 UTC, Daniela0531 commented
сделала одно активити, навигация через nav_graph

2024-04-22 16:37 UTC, Ksalim01 commented
Пройдусь по пунктам из тз и сразу выставлю баллы
1. (2) Стек работаетт очень странно, например если сделать последовательность нажатий читать->истории->читать->истории, то в стеке 4 экрана, а не 2, что на мой взгляд странное поведение
2. (0) экран с регистрацией показывается каждый раз
3. (0.5) ок
4. (0) креш при переходе в ландскейп
5. (1) ничего не изменилось, такое количество баллов и оставил
6. (0) не нашел
7. (0) не нашел
8. (0) дефолтная иконка 

Итог за первый этап - 3.5

2024-04-22 16:38 UTC, merged